// data/decals.json + data/brands.json -> src/brands.js
//
// Two layers, lowest first:
//
//   data/decals.json       generated by tools/build-decals.py from harvested
//                          favicons — real logos and colours guessed from
//                          pixels, for the ~70% of companies whose site still
//                          serves a usable icon.
//   data/simple-icons.json generated by tools/build-simple-icons.mjs — official
//                          published brand colours and clean single-path marks.
//                          Better than a favicon wherever it reaches, but it
//                          only covers ~11%.
//   data/brands.json       hand-curated, and always wins. This is where a bad
//                          automatic extraction gets corrected and where
//                          companies with no reachable site get a mark by hand.
//
// Anything in neither still gets a camera — content.js falls back to a monogram
// on a hashed colour — so a company can never go unreported.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const curated = JSON.parse(readFileSync(join(ROOT, "data/brands.json"), "utf8"));
const layer = (name) => {
  const f = join(ROOT, "data", name);
  return existsSync(f) ? JSON.parse(readFileSync(f, "utf8")) : {};
};
const decals = layer("decals.json");
const official = layer("simple-icons.json");
const registry = JSON.parse(readFileSync(join(ROOT, "data/registry.json"), "utf8"));
const known = new Set(registry.map((r) => r.id));

const brands = {};
for (const source of [decals, official]) {
  for (const [id, d] of Object.entries(source)) {
    if (!known.has(id)) continue;  // a company dropped by a registry refresh
    const { src, ...rest } = d;    // src is provenance for review, not runtime
    brands[id] = rest;
  }
}
for (const [id, c] of Object.entries(curated)) brands[id] = c;

// icons/brands/ is not committed. tools/fetch-logos.mjs downloads the artwork
// from the URLs data/decals.json records, and a company can drop off that list
// at any time: its site starts refusing an automated request, or the icon moves.
//
// A mark whose file is not there renders as nothing on the barrel, which reads
// as a broken camera rather than a missing logo. So resolve it here: the entry
// loses its mark and content.js gives that company a monogram instead. Doing it
// at build time rather than at runtime keeps tools/package.mjs able to insist,
// absolutely, that every mark it is about to zip up exists.
{
  const wanted = Object.entries(brands)
    .filter(([, b]) => typeof b.mark === "string" && b.mark.startsWith("icons/"));
  const missing = wanted.filter(([, b]) => !existsSync(join(ROOT, b.mark)));
  // Losing nearly all of them means the fetch was never run, not that 265
  // companies changed their icon on the same day. Refuse rather than quietly
  // generate a de-branded bundle that someone then commits.
  if (wanted.length && missing.length > wanted.length / 2) {
    console.error(
      `${missing.length} of ${wanted.length} logo files are missing from icons/brands/.\n\n` +
      "  node tools/fetch-logos.mjs\n" +
      "  python3 tools/build-decals.py --restore\n"
    );
    process.exit(1);
  }
  for (const [id] of missing) delete brands[id];
  if (missing.length) {
    console.error(
      `  ${missing.length} logo(s) unavailable, falling back to a monogram: ` +
      missing.map(([id]) => id).join(", ")
    );
  }
}

const REQUIRED = ["band", "palette", "mark", "decalW", "decalH"];

// Relative luminance of a hex colour; null for anything else (hsl monograms).
function lumOf(colour) {
  const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(colour);
  if (!m) return null;
  let h = m[1];
  if (h.length === 3) h = h.split("").map((c) => c + c).join("");
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
const problems = [];

for (const [id, b] of Object.entries(curated)) {
  if (!known.has(id)) problems.push(`${id}: not a company id in data/registry.json`);
}
for (const [id, b] of Object.entries(brands)) {
  for (const k of REQUIRED) {
    if (b[k] === undefined) problems.push(`${id}: missing "${k}"`);
  }
  if (b.palette && (!Array.isArray(b.palette) || !b.palette.length)) {
    problems.push(`${id}: "palette" must be a non-empty array`);
  }
  // The mark is injected with innerHTML into a closed shadow root. It is our
  // own hand-authored content, but keep it to inert drawing markup regardless.
  if (typeof b.mark === "string" && /<\s*(script|foreignObject|iframe)\b/i.test(b.mark)) {
    problems.push(`${id}: "mark" contains active content`);
  }
  // Whether the file is on disk is settled before this loop — icons/brands/ is
  // fetched at build time, so an absent logo is an ordinary outcome rather than
  // a mistake in the data. See the resolution step above.
  if (typeof b.band === "string" && !/^#[0-9a-f]{3,8}$|^hsl\(|^rgb\(/i.test(b.band)) {
    problems.push(`${id}: "band" is not a colour: ${b.band}`);
  }
  // Same contrast rule tools/build-decals.py applies, so a hand-curated entry
  // is held to exactly the standard the generated ones are. A mark that does
  // not separate from what it sits on renders as a blank disc, and that looks
  // like a broken camera rather than a missing logo — which is how TikTok and
  // WordPress were lost when their plate was set by hand.
  const MIN_CONTRAST = 0.34;
  const whiteSvg = typeof b.mark === "string" && b.mark.startsWith("<svg") &&
                   /fill="#fff"/i.test(b.mark) && !/fill="#(?!fff)/i.test(b.mark);
  const markLum = whiteSvg ? 1 : (decals[id] || {}).markLum;
  if (markLum !== undefined && typeof b.band === "string") {
    const backdrop = b.plate ? 1 : lumOf(b.band);
    if (backdrop !== null && Math.abs(markLum - backdrop) < MIN_CONTRAST) {
      problems.push(
        `${id}: mark (${markLum.toFixed(2)}) barely separates from ` +
          `${b.plate ? "the white plate" : `band ${b.band}`} — ` +
          `${b.plate ? 'drop "plate"' : "darken the band"}`
      );
    }
  }
}

if (problems.length) {
  for (const p of problems) console.error("  " + p);
  throw new Error(`${problems.length} problem(s) in data/brands.json`);
}

writeFileSync(
  join(ROOT, "src/brands.js"),
  "// GENERATED by tools/build-brands.mjs from data/brands.json — do not edit.\n" +
    "//\n" +
    "// Curated logos and brand colours, keyed by tracker id. Trackers absent\n" +
    "// from this table fall back to a monogram in content.js.\n" +
    "window.__cpBrands = " +
    JSON.stringify(brands) +
    ";\n"
);

const n = Object.keys(brands).length;
const pct = ((n / registry.length) * 100).toFixed(0);
const kb = (JSON.stringify(brands).length / 1024).toFixed(0);
console.log(
  `src/brands.js: ${n} of ${registry.length} companies branded (${pct}%), ${kb} KB\n` +
    `               ${Object.keys(decals).length} harvested, ` +
    `${Object.keys(official).length} official, ` +
    `${Object.keys(curated).length} hand-curated, ` +
    `${registry.length - n} on the monogram fallback`
);
